### ISSUE TITLE
LNK launcher not working

### ISSUE THREAD

**Issue by quandris1110** [Wintermute0110/plugin.program.AEL#137]
Just installed the Python 3 branch - excited to be able to test this! LKN launcher on Windows errors with the following message in the log:

```
2021-06-01 22:20:39.124 T:10116    INFO <general>: AEL INFO : _command_run_rom() Launching ROM in Launcher ...
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() Using Launcher standard arguments
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() Sigle ROM detected (no multidisc)
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() ROMFileName OP "C:\Users\Me\Documents\Shortcuts\Nioh 2 - Complete Edition.lnk"
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() ROMFileName  P "C:\Users\Me\Documents\Shortcuts\Nioh 2 - Complete Edition.lnk"
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() categoryID   root_category
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() launcherID   c20a033f7d256023cb0fea4223c38bbb
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() romID        fd2ebc961ee7c959aaeb33e25ba79648
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() romfile      "C:\Users\Me\Documents\Shortcuts\Nioh 2 - Complete Edition.lnk"
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() rompath      "C:\Users\Me\Documents\Shortcuts"
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() rombase      "Nioh 2 - Complete Edition.lnk"
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() rombasenoext "Nioh 2 - Complete Edition"
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() romtitle     "Nioh 2 - Complete Edition"
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() application  "lnk_launcher_app"
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() apppath      ""
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : _command_run_rom() romext       "lnk"
2021-06-01 22:20:39.125 T:10116    INFO <general>: AEL INFO : Launching app found "lnk_launcher_app"
2021-06-01 22:20:39.126 T:10116    INFO <general>: AEL INFO : ROM found "C:\Users\Me\Documents\Shortcuts\Nioh 2 - Complete Edition.lnk"
2021-06-01 22:20:39.126 T:10116    INFO <general>: AEL INFO : _command_run_rom() raw arguments   "%rom%"
2021-06-01 22:20:39.126 T:10116    INFO <general>: AEL INFO : _command_run_rom() final arguments "C:\Users\Me\Documents\Shortcuts\Nioh 2 - Complete Edition.lnk"
2021-06-01 22:20:39.127 T:10116    INFO <general>: AEL INFO : fs_write_Favourites_JSON() File special://profile/addon_data\plugin.program.advanced.emulator.launcher\most_played.json
2021-06-01 22:20:39.127 T:10116    INFO <general>: AEL INFO : _command_run_rom() Launcher is not Kodi Retroplayer.
2021-06-01 22:20:39.628 T:10116   ERROR <general>: AEL ERROR: SingleInstance::__exit__() Unhandled excepcion in protected code
2021-06-01 22:20:39.640 T:10116   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: bytes args is not allowed on Windows
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Me\Apps\Kodi19\portable_data\addons\plugin.program.advanced.emulator.launcher\addon.py", line 37, in <module>
                                                       main.Main().run_plugin(sys.argv)
                                                     File "C:\Users\Me\Apps\Kodi19\portable_data\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 411, in run_plugin
                                                       self.run_protected(command, args)
                                                     File "C:\Users\Me\Apps\Kodi19\portable_data\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 511, in run_protected
                                                       self._command_run_rom(args['catID'][0], args['launID'][0], args['romID'][0])
                                                     File "C:\Users\Me\Apps\Kodi19\portable_data\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 8181, in _command_run_rom
                                                       self._run_process(application.getPath(), arguments, apppath, romext, non_blocking_flag)
                                                     File "C:\Users\Me\Apps\Kodi19\portable_data\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 8232, in _run_process
                                                       retcode = subprocess.call('start "AEL" /b "{}"'.format(arguments).encode('utf-8'), shell = True)
                                                     File "C:\Users\Me\Apps\Kodi19\system\python\Lib\subprocess.py", line 340, in call
                                                       with Popen(*popenargs, **kwargs) as p:
                                                     File "C:\Users\Me\Apps\Kodi19\system\python\Lib\subprocess.py", line 854, in __init__
                                                       self._execute_child(args, executable, preexec_fn, close_fds,
                                                     File "C:\Users\Me\Apps\Kodi19\system\python\Lib\subprocess.py", line 1239, in _execute_child
                                                       raise TypeError('bytes args is not allowed on Windows')
                                                   TypeError: bytes args is not allowed on Windows
                                                   -->End of Python script error report<--
```

**Comment by Wintermute0110** [comment]
Should be fixed now. Please try.

**Comment by quandris1110** [comment]
That did the trick -- thanks!
