### ISSUE TITLE
Error when scraping metadata

### ISSUE THREAD

**Issue by Hybrid512** [Wintermute0110/plugin.program.AEL#146]
Hi,

For unknow reason, with some roms, I have an error when scraping metadata.
I have the same issue wether I'm using ScreeScraper or TGDB and this happens on some roms but not all (most are working as expected).
Didn't find any clue on what triggers the error though (doesn't seem to be related to the filename, even some roms without exotic characters and very simple filename.

Here is a debug log :

```
2021-06-25 15:26:55.133 T:52614    INFO <general>: initializing python engine.
2021-06-25 15:26:55.497 T:52614    INFO <general>: AEL DEBUG: ---------- Called AEL Main::run_plugin() constructor ----------
2021-06-25 15:26:55.497 T:52614    INFO <general>: AEL DEBUG: sys.platform   "linux"
2021-06-25 15:26:55.497 T:52614    INFO <general>: AEL DEBUG: Python version "3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]"
2021-06-25 15:26:55.497 T:52614    INFO <general>: AEL DEBUG: addon_id       "plugin.program.advanced.emulator.launcher"
2021-06-25 15:26:55.497 T:52614    INFO <general>: AEL DEBUG: addon_version  "0.10.1-alpha"
2021-06-25 15:26:55.497 T:52614    INFO <general>: AEL DEBUG: addon_argv[0] "plugin://plugin.program.advanced.emulator.launcher/"
2021-06-25 15:26:55.497 T:52614    INFO <general>: AEL DEBUG: addon_argv[1] "-1"
2021-06-25 15:26:55.497 T:52614    INFO <general>: AEL DEBUG: addon_argv[2] "?com=EDIT_ROM&catID=root_category&launID=d6ff01c1a806785ccf2756c2d68073a2&romID=b04cbf0a356b0bd6021cc0ac63ca643f"
2021-06-25 15:26:55.497 T:52614    INFO <general>: AEL DEBUG: addon_argv[3] "resume:false"
2021-06-25 15:26:55.497 T:52614    INFO <general>: AEL DEBUG: JSON version "Kodi" "19" "1" "20210509-85e05228b4" "stable"
2021-06-25 15:26:55.497 T:52614    INFO <general>: AEL DEBUG: JSON skin    "skin.estuary.AEL"
2021-06-25 15:26:55.514 T:52614    INFO <general>: AEL DEBUG: content_type = None
2021-06-25 15:26:55.514 T:52614    INFO <general>: AEL DEBUG: utils_load_XML_to_ET() Loading /home/kodi/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher/categories.xml
2021-06-25 15:26:55.515 T:52614    INFO <general>: AEL DEBUG: command = "EDIT_ROM"
2021-06-25 15:26:55.515 T:52614    INFO <general>: AEL DEBUG: SingleInstance::__enter__() Lock not in use. Setting lock
2021-06-25 15:26:55.515 T:52614    INFO <general>: AEL DEBUG: Advanced Emulator Launcher run_protected() BEGIN
2021-06-25 15:26:55.515 T:52614    INFO <general>: AEL DEBUG: _command_edit_rom() Editing ROM in Launcher
2021-06-25 15:26:55.515 T:52614    INFO <general>: AEL DEBUG: fs_load_ROMs_JSON()  Dir special://profile/addon_data/plugin.program.advanced.emulator.launcher/db_ROMs
2021-06-25 15:26:55.515 T:52614    INFO <general>: AEL DEBUG: fs_load_ROMs_JSON() JSON roms_root_category_Nintendo_Wii_d6ff01.json
2021-06-25 15:26:55.515 T:52614    INFO <general>: AEL DEBUG: utils_load_JSON_file() "/home/kodi/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher/db_ROMs/roms_root_category_Nintendo_Wii_d6ff01.json"
2021-06-25 15:26:57.220 T:52614    INFO <general>: AEL DEBUG: ScraperFactory.__init__() Creating scraper objects...
2021-06-25 15:26:57.220 T:52614    INFO <general>: AEL DEBUG: AEL_Offline.__init__() Setting addon dir "/home/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher"
2021-06-25 15:26:57.221 T:52614    INFO <general>: AEL DEBUG: ScreenScraper.__init__() User preferred region "wor"
2021-06-25 15:26:57.221 T:52614    INFO <general>: AEL DEBUG: ScreenScraper.__init__() User preferred language "fr"
2021-06-25 15:26:57.221 T:52614    INFO <general>: AEL DEBUG: ScraperFactory.get_metadata_scraper_menu_list() Building scraper list...
2021-06-25 15:26:57.221 T:52614    INFO <general>: AEL DEBUG: Scraper Null lacks metadata (DISABLED)
2021-06-25 15:26:57.221 T:52614    INFO <general>: AEL DEBUG: Scraper AEL Offline supports metadata (ENABLED)
2021-06-25 15:26:57.221 T:52614    INFO <general>: AEL DEBUG: Scraper TheGamesDB supports metadata (ENABLED)
2021-06-25 15:26:57.221 T:52614    INFO <general>: AEL DEBUG: Scraper MobyGames supports metadata (ENABLED)
2021-06-25 15:26:57.221 T:52614    INFO <general>: AEL DEBUG: Scraper ScreenScraper supports metadata (ENABLED)
2021-06-25 15:26:57.221 T:52614    INFO <general>: AEL DEBUG: Scraper ArcadeDB supports metadata (ENABLED)
2021-06-25 15:26:59.284 T:52614    INFO <general>: AEL DEBUG: ScraperFactory.create_CM_metadata() Creating ScrapeStrategy ID 50
2021-06-25 15:26:59.284 T:52614    INFO <general>: AEL DEBUG: ScrapeStrategy.__init__() Initializing ScrapeStrategy...
2021-06-25 15:26:59.284 T:52614    INFO <general>: AEL DEBUG: User chose scraper "ScreenScraper"
2021-06-25 15:26:59.284 T:52614    INFO <general>: AEL DEBUG: self.strategy_obj.scan_ignore_scrap_title is True
2021-06-25 15:26:59.284 T:52614    INFO <general>: AEL DEBUG: ScrapeStrategy.scrap_CM_metadata_ROM() BEGIN ...
2021-06-25 15:26:59.285 T:52614    INFO <general>: AEL DEBUG: ScreenScraper.check_before_scraping() ScreenScraper user name and pass OK.
2021-06-25 15:26:59.285 T:52614   ERROR <general>: AEL ERROR: SingleInstance::__exit__() Unhandled excepcion in protected code
2021-06-25 15:26:59.285 T:52614    INFO <general>: AEL DEBUG: SingleInstance::__exit__() Releasing lock
2021-06-25 15:26:59.290 T:52614   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'ROM_FN'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 37, in <module>
                                                       resources.main.Main().run_plugin(sys.argv)
                                                     File "/home/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 411, in run_plugin
                                                       self.run_protected(command, args)
                                                     File "/home/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 507, in run_protected
                                                       self._command_edit_rom(args['catID'][0], args['launID'][0], args['romID'][0])
                                                     File "/home/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 2889, in _command_edit_rom
                                                       s_strategy.scrap_CM_metadata_ROM(object_dic, data_dic, st_dic)
                                                     File "/home/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/scrap.py", line 1086, in scrap_CM_metadata_ROM
                                                       self._scrap_CM_get_candidate(ScrapeStrategy.SCRAPE_ROM, object_dic, data_dic, st_dic)
                                                     File "/home/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/scrap.py", line 1226, in _scrap_CM_get_candidate
                                                       ROM_FN = data_dic['ROM_FN']
                                                   KeyError: 'ROM_FN'
                                                   -->End of Python script error report<--
                                                   
2021-06-25 15:26:59.390 T:52614    INFO <general>: Python interpreter stopped
```

**Comment by Wintermute0110** [comment]
Should be fixed now, please try.
